from __future__ import annotations

from pathlib import Path
from typing import List

from planner_generator.listing_assets.carousel import write_etsy_listing_carousel
from planner_generator.market_intelligence.models import NicheBrief
from planner_generator.planner_specs.models import BundleSpec, PageSpec
from planner_generator.product_generation.previews import write_product_page_previews
from planner_generator.theme_engine.models import Theme


def write_listing_preview_assets(
    output_dir: str | Path,
    bundle: BundleSpec,
    theme: Theme,
    pages: List[PageSpec],
    market_brief: NicheBrief | None = None,
) -> List[Path]:
    """Compatibility wrapper for older callers.

    Listing images are now generated by the dedicated Etsy carousel module, and
    factual page previews live in the product-generation pipeline. New code
    should call those modules directly so the two generation paths stay separate.
    """

    listing_images = write_etsy_listing_carousel(output_dir, bundle, theme, pages, market_brief)
    product_previews = write_product_page_previews(output_dir, theme, pages)
    return listing_images + product_previews
